sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.0
  - 5.6

install:
  - composer self-update --no-interaction
  - composer install --no-interaction --prefer-dist

before_script:
    - vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs/

script:
    - vendor/bin/phpcs --standard=ruleset.xml