name: Test
on: [push]

jobs:
  build:
    strategy:
      matrix:
        php: ['7.4']
      fail-fast: false
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install PHP
      uses: shivammathur/setup-php@2.7.0
      with:
        php-version: ${{ matrix.php }}

    - name: Debugging
      run: |
        php --version
        php -m
        composer --version

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-suggest

    - name: Run tests
      run: composer run test
